### ISSUE TITLE
has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource.

### ISSUE THREAD

**Issue by EyyupUlutas** [emresenyuva/youtube-music-api#11]
<img width="583" alt="Ekran Resmi 2021-05-12 21 46 39" src="https://user-images.githubusercontent.com/52197552/118028243-8a69e380-b36b-11eb-8227-48f687133f86.png">

I am constantly encountering this problem, I am changing the axios settings, I am giving cors permission, but this time I am getting **Refused to set unsafe header "User-Agent" error.**

How can I fix this error?

**Comment by emresenyuva** [comment]
if you use this package with electron, you must change axios adapter in index.js. 
```
const axios = require('axios');
axios.defaults.adapter = require('axios/lib/adapters/http');
```

**Comment by emresenyuva** [comment]
check https://github.com/emresenyuva/youtube-music-api/commit/e206c9affec32ff50371d135d0b5bdf1944e6c8d

**Comment by EyyupUlutas** [comment]
YouTube **React JS** app I need to pull **artist names and browseid** with a website encoding music-related data I want to use it for this I tried the API app you wrote, the solution you suggested didn't work, but the error still persists are there other **alternatives** ?
**API thank you for your very good efforts**  @emresenyuva
