### ISSUE TITLE
PLEASE+++++++++ help

### ISSUE THREAD

**Issue by Intronet** [emresenyuva/youtube-music-api#13]
Can you publish an example showing how to get the continuations for videos and playlists

**Comment by Intronet** [comment]
OK got the continuations working
index.js line 219  if (contentLimit > result.content.length) {
replace with if (result.trackCount > result.content.length) {

**Comment by zS1L3NT** [comment]
You're asking us to edit the source code?

**Comment by Intronet** [comment]
> You're asking us to edit the source code?

Yes, and it will return all videos in a playlist
