### ISSUE TITLE
Invalid Header value

### ISSUE THREAD

**Issue by aldrinjenson** [emresenyuva/youtube-music-api#6]
Hi, first of all I'd like to say a big thank you to you for making this wonderful package! 🥳 
 
I tried hosting my project which uses this api on a server and I got the following error.
Could you please provide some insight on this 🤞🏼 

![image](https://user-images.githubusercontent.com/53407417/105983940-756c8b80-60bf-11eb-8f3a-81145e436486.png)

**Comment by itsmrTech** [comment]
+1
@aldrinjenson Have you found any fixes?

**Comment by aldrinjenson** [comment]
No, I'm afraid not @itsmrTech 
I think the error happens here though: https://github.com/emressenyuva/youtube-music-api/blob/d740345371df46765c83ad45b529628b1a8d8bd3/src/index.js#L49

If you find any alternative package, kindly mention here as well please.

**Comment by emresenyuva** [comment]
fixed at https://github.com/emresenyuva/youtube-music-api/commit/b52b2b0d3fd146face64d193ba333c948e857451
