### ISSUE TITLE
Invalid value "undefined" for header "X-Goog-Visitor-Id"

### ISSUE THREAD

**Issue by itsmrTech** [emresenyuva/youtube-music-api#9]
Hey. Today I'm getting this error message when I want to search in songs. Could anyone know what's wrong?

**Comment by annata83** [comment]
Seems like this project is been abandon; What do you think?

**Comment by emresenyuva** [comment]
fixed at https://github.com/emresenyuva/youtube-music-api/commit/b52b2b0d3fd146face64d193ba333c948e857451

**Comment by emresenyuva** [comment]
fixed at https://github.com/emresenyuva/youtube-music-api/commit/b52b2b0d3fd146face64d193ba333c948e857451
